version: "3"

services:
  webserver:
    image: nginx:alpine
    container_name: aegtcp-webserver
    ports:
      - "13985:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  src:
