apiVersion: v1
kind: Service
metadata:
  name: { { include "engineers-guide-to-cerebral-palsy.fullname" . } }
  labels:
    { { - include "engineers-guide-to-cerebral-palsy.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {
      {
        - include "engineers-guide-to-cerebral-palsy.selectorLabels" . | nindent 4,
      },
    }
